insert into games values
  (1, 'brute-force-password-cracker', 'Brute Force Password Cracker', 'I built the Brute Force Password Cracker as a fun program to test out passwords, and to test my knowledge of Python 3 and its libraries', 'https://repl.it/talk/share/Brute-Force-Password-Cracker/4336', 'CyanCoding', 'Brute-Force-Password-Cracker', 812),
  (2, 'webgl-rolling-sky', 'WebGL Rolling Sky', 'One of my older projects. Used the Three.js library. 100% made by me! How to play: Click or touch the screen to start', 'https://repl.it/talk/share/New-levels-WebGL-Rolling-Sky/3791', 'JSer', 'rolling-sky--jser', 712),
  (3, 'shakespearean-insult-generator', 'Shakespearean Insult Generator', 'Shakespearean Insult Generator', 'https://repl.it/talk/share/Shakespearean-Insult-Generator/3382', 'JJCTPMS', 'Shakespearean-Insult-Generator', 556),
  (4, 'tic-tac-toe', 'Tic-Tac-Toe', 'As a fun side project, I built this awesome Tic-Tac-Toe game (with three AI levels) in May 2017', 'https://repl.it/talk/share/Tic-Tac-Toe/4341', 'CyanCoding', 'Tic-Tac-Toe', 356),
  (5, 'gold-hunt', 'Gold Hunt', 'Hunt the golden ball and avoid the dangerous obstacles that can damage your score!', 'https://repl.it/talk/share/Gold-Hunt/3463', 'dosmaster4life', 'gold-hunt', 320),
  (6, 'the-fishing-game', 'The Fishing Game', 'Explore your way through the different regions by catching the rarest fish you can. Catch em all to fill up your fishedex!', 'https://repl.it/talk/share/The-Fishing-Game/12016', 'AmeliaBlackwell', 'the-fishing-game', 261),
  (7, 'kars', 'Kars', 'A survival driving game. Use arrow keys to move, avoid the trees, and collect fuel!', 'https://repl.it/talk/share/Kars/3911', 'ALVINWAN1', 'Kars', 256),
  (8, 'the-dark-forest', 'The Dark Forest', 'You are lost in the forest and you are trying to get out of it and find your way back to civilization. (Hopefully) You will find a dog. Try to tame it', 'https://repl.it/talk/share/The-Dark-Forest/20827', 'DJWang', 'The-Dark-Dark-Forest', 220),
  (9, 'minecraft-webgl-project-core', 'Minecraft WebGL Project Core', 'This is the final version of my WebCraft and MC-Engine projects. I merged them into one, and added a menu', 'https://repl.it/talk/share/Minecraft-WebGL-Project-Core/29550', 'HENRYMARTIN4', 'minecraft', 192),
  (10, 'adventure-game', 'Adventure Game', 'It was for one of my school projects, but i still thought it was good', 'https://repl.it/talk/share/Adventure-Game/4293', 'AidanMott', 'Adventure-Game', 186),
  (11, 'three-ways', 'Three Ways', 'This is my three ways game. You can move the ball with k, l, and m or arrows. Press enter to play and retry. It''s better to play in a new tab. I hope you will enjoy it', 'https://repl.it/talk/share/Three-Ways/12058', 'Equation', 'Three-Ways-Game', 171),
  (12, '3d-online-multiplayer-shooter', '3D Online Multiplayer Shooter', 'Featured in the Repl.it Newsletter. Made with pure JS (Node.js for server-side). Used the Three.js and Socket.io libraries', 'https://repl.it/talk/share/3D-Online-Multiplayer-Shooter/5323', 'JSer', '3D', 171),
  (13, 'krossy-road', 'Krossy Road', 'This game was developed for educational purposes for Bit By Bit (http://littlebitbybit.org). Worldwide high scores aren''t available yet, but based on my personal experience of watching other people play, the current record is 429. Have fun!', 'https://repl.it/talk/share/Krossy-Road/3088', 'derekwan', 'KrossyRoad', 167);
